:- module(facts,[]).
wine(maibec).
wine(syrah).
wine(mourvedre).
wine(pinotage).
wine(petite_sirah).
wine(touriga_nacional).
wine(cabernet_sauvignon).
wine(bordeaux_blend).
wine(meritage).
wine(meriot).
wine(sangiovese).
wine(zinfandel).
wine(cabernet_franc).
wine(tempranillo).
wine(nebbiolo).
wine(barbera).
wine(cotes_du_rhone_blend).
wine(pinot_noir).
wine(grenache).
wine(gamay).
wine(st._laurent).
wine(carignan).
wine(counoise).
wine(provencal_rose).
wine(white_zinfandel).
wine(loire_valley_rose).
wine(pinot_noir_rose).
wine(garnacha_rosadp).
wine(bandol_rose).
wine(tempranillio_rose).
wine(saignee_method_rose).
wine(chardonnay).
wine(semillon).
wine(viognier).
wine(marsanne).
wine(roussanne).
wine(sauvignon_blanc).
wine(albarino).
wine(pinot_blanc).
wine(vermentino).
wine(melon_de_bourgogne).
wine(gargenega).
wine(trebbiano).
wine(pinot_gris).
wine(pinot_grigio).
wine(champagne).
wine(prosecco).
wine(cremant).
wine(cava).
wine(metodo_classico).
wine(sparkling_wine).
wine(sparkling_rose).
wine(moscato).
wine(riesling).
wine(chenin_blanc).
wine(gewurztraminer).
wine(late_harvest_whites).
wine(alsacian_pinot_gris).
wine(port).
wine(sherry).
wine(madeira).
wine(vin_santo).
wine(muscat).
wine(pedro_ximenez).

wineType(bold_red).
wineType(medium_red).
wineType(light_red).
wineType(rose).
wineType(rich_white).
wineType(light_white).
wineType(sparkling).
wineType(sweet_white).
wineType(dessert).

hasMinorType(beef,red_meat).
hasMinorType(lamb,red_meat).
hasMinorType(salami,cured_meat).
hasMinorType(proscuitto,cured_meat).
hasMinorType(brosaola,cured_meat).
hasMinorType(bacon,cured_meat).
hasMinorType(roast.pork).
hasMinorType(tenderloin,pork).
hasMinorType(pork_chop,pork).
hasMinorType(chicken,poultry).
hasMinorType(duck,poultry).
hasMinorType(turkey,poultry).
hasMinorType(oyster,mollusk).
hasMinorType(mussel,mollusk).
hasMinorType(clam,mollusk).
hasMinorType(tuna,fish).
hasMinorType(cod,fish).
hasMinorType(trout,fish).
hasMinorType(bass,fish).
hasMinorType(prawn,lobster_shell_fish).
hasMinorType(crab,lobster_shell_fish).
hasMinorType(langoustine,lobster_shell_fish).
hasMinorType(bleu,pungent_cheese).
hasMinorType(gargonzola,pungent_cheese).
hasMinorType(stilton,pungent_cheese).
hasMinorType(green_bean,green_vegetables).
hasMinorType(kale,green_vegetables).
hasMinorType(lettuce,green_vegetables).
hasMinorType(turnip,root_vegetables).
hasMinorType(butternut,root_vegetables).
hasMinorType(pumpkin,root_vegetables).
hasMinorType(delicata,root_vegetables).
hasMinorType(carrot,root_vegetables).
hasMinorType(tomato,nightshades).
hasMinorType(eggplant,nightshades).
hasMinorType(bell_pepper,nightshades).
hasMinorType(crimini,funghi).
hasMinorType(maitake,funghi).
hasMinorType(chenterelle,funghi).
hasMinorType(peanut,nuts_seeds).
hasMinorType(almond,nuts_seeds).
hasMinorType(pecan,nuts_seeds).
hasMinorType(sesame,nuts_seeds).
hasMinorType(lentil,beans_peas).
hasMinorType(navy,beans_peas).
hasMinorType(pinto,beans_peas).
hasMinorType(chickpea,beans_peas).
hasMinorType(black_pepper,black_pepper).
hasMinorType(ancho,hot_spicy).
hasMinorType(aleppo,hot_spicy).
hasMinorType(chipotle,hot_spicy).
hasMinorType(sichuan,hot_spicy).
hasMinorType(thyme,herbs).
hasMinorType(oregano,herbs).
hasMinorType(basil,herbs).
hasMinorType(tarragon,herbs).
hasMinorType(cinnamon,baking_spices).
hasMinorType(clove,baking_spices}.
hasMinorType(allspice,baking_spices).
hasMinorType(mace,baking_spices).
hasMinorType(anise,exotic_aromatic_spices).
hasMinorType(turmeric,exotic_aromatic_spices).
hasMinorType(saffron,exotic_aromatic_spices).
hasMinorType(fennel,exotic_aromatic_spices).
hasMinorType(ginger,exotic_aromatic_spices).
hasMinorType(flour,white_starches).
hasMinorType(white_rice,white_starches).
hasMinorType(pasta,white_starches).
hasMinorType(bread,white_starches).
hasMinorType(tortillas,white_starches).
hasMinorType(quinoa,whole_wheat_grains).
hasMinorType(farro,whole_wheat_grains).
hasMinorType(brown_rice,whole_wheat_grains).
hasMinorType(sweet_potato,sweet_starchy_vegetables).
hasMinorType(yucca,sweet_starchy_vegetables).
hasMinorType(taro,sweet_starchy_vegetables).
hasMinorType(potato,potato).
hasMinorType(strawberry,fruit_berries).
hasMinorType(orange,fruit_berries).
hasMinorType(apple,fruit_berries).
hasMinorType(papaya,fruit_berries).
hasMinorType(mango,fruit_berries).
hasMinorType(peach,fruit_berries).
hasMinorType(cherry,fruit_berries).
hasMinorType(banana,fruit_berries).
hasMinorType(creme_brulee,vanilla_caramel).
hasMinorType(ice_cream,vanilla_caramel).
hasMinorType(chocolate,chocolate_coffee).
hasMinorType(coffee,chocolate_coffee).

hasMajorType(red_meat,meat).
hasMajorType(cured_meat,meat).
hasMajorType(pork,meat).
hasMajorType(poultry,meat).
hasMajorType(mollusk,meat).
hasMajorType(fish,meat).
hasMajorType(lobster_shell_fish,fish).
hasMajorType(soft_cheese,dairy).
hasMajorType(cream,dairy).
hasMajorType(pungent_cheese,dairy).
hasMajorType(hard_cheese,dairy).
hasMajorType(alliums,vegetable).
hasMajorType(green_vegetables,vegetable).
hasMajorType(root_vegetables,vegetable).
hasMajorType(nightshades,vegetable).
hasMajorType(funghi,vegetable).
hasMajorType(nuts_seeds,vegetable).
hasMajorType(beans_peas,vegetable).
hasMajorType(black_pepper,herb_spice).
hasMajorType(red_pepper,herb_spice).
hasMajorType(hot_spicy,herb_spice).
hasMajorType(herbs,herb_spice).
hasMajorType(baking_spices,herb_spice).
hasMajorType(exotic_aromatic_spices,herb_spice).
hasMajorType(white_starches,starch).
hasMajorType(whole_wheat_grains,starch).
hasMajorType(sweet_starchy_vegetables,starch).
hasMajorType(potato,starch).
hasMajorType(fruit_berries,sweet).
hasMajorType(vanilla_caramel,sweet).
hasMajorType(chocolate_coffee,sweet).