:- module(facts,[]).
<<<<<<< HEAD
wine(maibec).
wine(syrah).
wine(mourvedre).
wine(pinotage).
wine(petite_sirah).
wine(touriga_nacional).
wine(cabernet_sauvignon).
wine(bordeaux_blend).
wine(meritage).
wine(meriot).
wine(sangiovese).
wine(zinfandel).
wine(cabernet_franc).
wine(tempranillo).
wine(nebbiolo).
wine(barbera).
wine(cotes_du_rhone_blend).
wine(pinot_noir).
wine(grenache).
wine(gamay).
wine(st._laurent).
wine(carignan).
wine(counoise).
wine(provencal_rose).
wine(white_zinfandel).
wine(loire_valley_rose).
wine(pinot_noir_rose).
wine(garnacha_rosadp).
wine(bandol_rose).
wine(tempranillio_rose).
wine(saignee_method_rose).
wine(chardonnay).
wine(semillon).
wine(viognier).
wine(marsanne).
wine(roussanne).
wine(sauvignon_blanc).
wine(albarino).
wine(pinot_blanc).
wine(vermentino).
wine(melon_de_bourgogne).
wine(gargenega).
wine(trebbiano).
wine(pinot_gris).
wine(pinot_grigio).
wine(champagne).
wine(prosecco).
wine(cremant).
wine(cava).
wine(metodo_classico).
wine(sparkling_wine).
wine(sparkling_rose).
wine(moscato).
wine(riesling).
wine(chenin_blanc).
wine(gewurztraminer).
wine(late_harvest_whites).
wine(alsacian_pinot_gris).
wine(port).
wine(sherry).
wine(madeira).
wine(vin_santo).
wine(muscat).
wine(pedro_ximenez).

wineType(bold_red).
wineType(medium_red).
wineType(light_red).
wineType(rose).
wineType(rich_white).
wineType(light_white).
wineType(sparkling).
wineType(sweet_white).
wineType(dessert).

hasMinorType(beef,red_meat).
hasMinorType(lamb,red_meat).
hasMinorType(salami,cured_meat).
hasMinorType(proscuitto,cured_meat).
hasMinorType(brosaola,cured_meat).
hasMinorType(bacon,cured_meat).
hasMinorType(roast.pork).
hasMinorType(tenderloin,pork).
hasMinorType(pork_chop,pork).
hasMinorType(chicken,poultry).
hasMinorType(duck,poultry).
hasMinorType(turkey,poultry).
hasMinorType(oyster,mollusk).
hasMinorType(mussel,mollusk).
hasMinorType(clam,mollusk).
hasMinorType(tuna,fish).
hasMinorType(cod,fish).
hasMinorType(trout,fish).
hasMinorType(bass,fish).
hasMinorType(prawn,lobster_shell_fish).
hasMinorType(crab,lobster_shell_fish).
hasMinorType(langoustine,lobster_shell_fish).
hasMinorType(bleu,pungent_cheese).
hasMinorType(gargonzola,pungent_cheese).
hasMinorType(stilton,pungent_cheese).
hasMinorType(green_bean,green_vegetables).
hasMinorType(kale,green_vegetables).
hasMinorType(lettuce,green_vegetables).
hasMinorType(turnip,root_vegetables).
hasMinorType(butternut,root_vegetables).
hasMinorType(pumpkin,root_vegetables).
hasMinorType(delicata,root_vegetables).
hasMinorType(carrot,root_vegetables).
hasMinorType(tomato,nightshades).
hasMinorType(eggplant,nightshades).
hasMinorType(bell_pepper,nightshades).
hasMinorType(crimini,funghi).
hasMinorType(maitake,funghi).
hasMinorType(chenterelle,funghi).
hasMinorType(peanut,nuts_seeds).
hasMinorType(almond,nuts_seeds).
hasMinorType(pecan,nuts_seeds).
hasMinorType(sesame,nuts_seeds).
hasMinorType(lentil,beans_peas).
hasMinorType(navy,beans_peas).
hasMinorType(pinto,beans_peas).
hasMinorType(chickpea,beans_peas).
hasMinorType(black_pepper,black_pepper).
hasMinorType(ancho,hot_spicy).
hasMinorType(aleppo,hot_spicy).
hasMinorType(chipotle,hot_spicy).
hasMinorType(sichuan,hot_spicy).
hasMinorType(thyme,herbs).
hasMinorType(oregano,herbs).
hasMinorType(basil,herbs).
hasMinorType(tarragon,herbs).
hasMinorType(cinnamon,baking_spices).
hasMinorType(clove,baking_spices}.
hasMinorType(allspice,baking_spices).
hasMinorType(mace,baking_spices).
hasMinorType(anise,exotic_aromatic_spices).
hasMinorType(turmeric,exotic_aromatic_spices).
hasMinorType(saffron,exotic_aromatic_spices).
hasMinorType(fennel,exotic_aromatic_spices).
hasMinorType(ginger,exotic_aromatic_spices).
hasMinorType(flour,white_starches).
hasMinorType(white_rice,white_starches).
hasMinorType(pasta,white_starches).
hasMinorType(bread,white_starches).
hasMinorType(tortillas,white_starches).
hasMinorType(quinoa,whole_wheat_grains).
hasMinorType(farro,whole_wheat_grains).
hasMinorType(brown_rice,whole_wheat_grains).
hasMinorType(sweet_potato,sweet_starchy_vegetables).
hasMinorType(yucca,sweet_starchy_vegetables).
hasMinorType(taro,sweet_starchy_vegetables).
hasMinorType(potato,potato).
hasMinorType(strawberry,fruit_berries).
hasMinorType(orange,fruit_berries).
hasMinorType(apple,fruit_berries).
hasMinorType(papaya,fruit_berries).
hasMinorType(mango,fruit_berries).
hasMinorType(peach,fruit_berries).
hasMinorType(cherry,fruit_berries).
hasMinorType(banana,fruit_berries).
hasMinorType(creme_brulee,vanilla_caramel).
hasMinorType(ice_cream,vanilla_caramel).
hasMinorType(chocolate,chocolate_coffee).
hasMinorType(coffee,chocolate_coffee).

hasMajorType(red_meat,meat).
hasMajorType(cured_meat,meat).
hasMajorType(pork,meat).
hasMajorType(poultry,meat).
hasMajorType(mollusk,meat).
hasMajorType(fish,meat).
hasMajorType(lobster_shell_fish,fish).
hasMajorType(soft_cheese,dairy).
hasMajorType(cream,dairy).
hasMajorType(pungent_cheese,dairy).
hasMajorType(hard_cheese,dairy).
hasMajorType(alliums,vegetable).
hasMajorType(green_vegetables,vegetable).
hasMajorType(root_vegetables,vegetable).
hasMajorType(nightshades,vegetable).
hasMajorType(funghi,vegetable).
hasMajorType(nuts_seeds,vegetable).
hasMajorType(beans_peas,vegetable).
hasMajorType(black_pepper,herb_spice).
hasMajorType(red_pepper,herb_spice).
hasMajorType(hot_spicy,herb_spice).
hasMajorType(herbs,herb_spice).
hasMajorType(baking_spices,herb_spice).
hasMajorType(exotic_aromatic_spices,herb_spice).
hasMajorType(white_starches,starch).
hasMajorType(whole_wheat_grains,starch).
hasMajorType(sweet_starchy_vegetables,starch).
hasMajorType(potato,starch).
hasMajorType(fruit_berries,sweet).
hasMajorType(vanilla_caramel,sweet).
hasMajorType(chocolate_coffee,sweet).
=======

IsWineType(maibec,bold_red).
IsWineType(syrah,bold_red).
IsWineType(mourvedre,bold_red).
IsWineType(pinotage,bold_red).
IsWineType(petite_sirah,bold_red).
IsWineType(touriga_nacional,bold_red).
IsWineType(cabernet_sauvignon,bold_red).
IsWineType(bordeaux_blend,bold_red).
IsWineType(meritage,bold_red).
IsWineType(meriot,medium_red).
IsWineType(sangiovese,medium_red).
IsWineType(zinfandel,medium_red).
IsWineType(cabernet_franc,medium_red).
IsWineType(tempranillo,medium_red).
IsWineType(nebbiolo,medium_red).
IsWineType(barbera,medium_red).
IsWineType(cotes_du_rhone_blend,medium_red).
IsWineType(pinot_noir,light_red).
IsWineType(grenache,light_red).
IsWineType(gamay,light_red).
IsWineType(st._laurent,light_red).
IsWineType(carignan,light_red).
IsWineType(counoise,light_red).
IsWineType(provencal_rose,rose).
IsWineType(white_zinfandel,rose).
IsWineType(loire_valley_rose,rose).
IsWineType(pinot_noir_rose,rose).
IsWineType(garnacha_rosadp,rose).
IsWineType(bandol_rose,rose).
IsWineType(tempranillio_rose,rose).
IsWineType(saignee_method_rose,rose).
IsWineType(chardonnay,rich_white).
IsWineType(semillon,rich_white).
IsWineType(viognier,rich_white).
IsWineType(marsanne,rich_white).
IsWineType(roussanne,rich_white).
IsWineType(sauvignon_blanc,light_white).
IsWineType(albarino,light_white).
IsWineType(pinot_blanc,light_white).
IsWineType(vermentino,light_white).
IsWineType(melon_de_bourgogne,light_white).
IsWineType(gargenega,light_white).
IsWineType(trebbiano,light_white).
IsWineType(pinot_gris,light_white).
IsWineType(pinot_grigio,light_white).
IsWineType(champagne,sparkling).
IsWineType(prosecco,sparkling).
IsWineType(cremant,sparkling).
IsWineType(cava,sparkling).
IsWineType(metodo_classico,sparkling).
IsWineType(sparkling_wine,sparkling).
IsWineType(sparkling_rose,sparkling).
IsWineType(moscato,sweet_white).
IsWineType(riesling,sweet_white).
IsWineType(chenin_blanc,sweet_white).
IsWineType(gewurztraminer,sweet_white).
IsWineType(late_harvest_whites,sweet_white).
IsWineType(alsacian_pinot_gris,sweet_white).
IsWineType(port,dessert).
IsWineType(sherry,dessert).
IsWineType(madeira,dessert).
IsWineType(vin_santo,dessert).
IsWineType(muscat,dessert).
IsWineType(pedro_ximenez,dessert).
compatible(red_meat,bold_red).
compatible(cured_meat,bold_red).
compatible(pork,bold_red).
compatible(pungent_cheese,bold_red).
compatible(hard_cheese,bold_red).
compatible(alliums,bold_red).
compatible(nightshades,bold_red).
compatible(funghi,bold_red).
compatible(black_pepper,bold_red).
compatible(red_pepper,bold_red).
compatible(white_starches,bold_red).
compatible(potato,bold_red).
compatible(red_meat,medium_red).
compatible(cured_meat,medium_red).
compatible(pork,medium_red).
compatible(soft_cheese_cream,medium_red).
compatible(pungent_cheese,medium_red).
compatible(hard_cheese,medium_red).
compatible(alliums,medium_red).
compatible(nightshades,medium_red).
compatible(funghi,medium_red).
compatible(beans_peas,medium_red).
compatible(black_pepper,medium_red).
compatible(herbs,medium_red).
compatible(baking_spices,medium_red).
compatible(exotic_aromatic_spices,medium_red).
compatible(white_starches,medium_red).
compatible(potato,medium_red).
compatible(cured_meat,light_red).
compatible(poultry,light_red).
compatible(soft_cheese_cream,light_red).
compatible(alliums,light_red).
compatible(funghi,light_red).
compatible(nuts_seeds,light_red).
compatible(herbs,light_red).
compatible(exotic_aromatic_spices,light_red).
compatible(white_starches,light_red).
compatible(whole_wheat_grains,light_red).
compatible(potato,light_red).
compatible(cured_meat,rose).
compatible(pork,rose).
compatible(poultry,rose).
compatible(soft_cheese_cream,rose).
compatible(pungent_cheese,rose).
compatible(hard_cheese,rose).
compatible(alliums,rose).
compatible(root_vegetables,rose).
compatible(nightshades,rose).
compatible(nuts_seeds,rose).
compatible(beans_peas,rose).
compatible(red_pepper,rose).
compatible(herbs,rose).
compatible(baking_spices,rose).
compatible(exotic_aromatic_spices,rose).
compatible(white_starches,rose).
compatible(whole_wheat_grains,rose).
compatible(sweet_starchy_vegetables,rose).
compatible(potato,rose).
compatible(poultry,rich_white).
compatible(fish,rich_white).
compatible(lobster_shell_fish,rich_white).
compatible(soft_cheese_cream,rich_white).
compatible(hard_cheese,rich_white).
compatible(alliums,rich_white).
compatible(root_vegetables,rich_white).
compatible(funghi,rich_white).
compatible(nuts_seeds,rich_white).
compatible(herbs,rich_white).
compatible(white_starches,rich_white).
compatible(whole_wheat_grains,rich_white).
compatible(potato,rich_white).
compatible(poultry,sparkling).
compatible(mollusk,sparkling).
compatible(fish,sparkling).
compatible(lobster_shell_fish,sparkling).
compatible(soft_cheese_cream,sparkling).
compatible(pungent_cheese,sparkling).
compatible(alliums,sparkling).
compatible(green_vegetables,sparkling).
compatible(nuts_seeds,sparkling).
compatible(beans_peas,sparkling).
compatible(red_pepper,sparkling).
compatible(hot_spicy,sparkling).
compatible(herbs,sparkling).
compatible(white_starches,sparkling).
compatible(potato,sparkling).
compatible(cured_meat,sweet_white).
compatible(lobster_shell_fish,sweet_white).
compatible(soft_cheese_cream,sweet_white).
compatible(pungent_cheese,sweet_white).
compatible(alliums,sweet_white).
compatible(root_vegetables,sweet_white).
compatible(nightshades,sweet_white).
compatible(nuts_seeds,sweet_white).
compatible(red_pepper,sweet_white).
compatible(hot_spicy,sweet_white).
compatible(baking_spices,sweet_white).
compatible(exotic_aromatic_spices,sweet_white).
compatible(white_starches,sweet_white).
compatible(whole_wheat_grains,sweet_white).
compatible(sweet_starchy_vegetables,sweet_white).
compatible(potato,sweet_white).
compatible(fruit_berries,sweet_white).
compatible(vanilla_caramel,sweet_white).
compatible(cured_meat,dessert).
compatible(soft_cheese_cream,dessert).
compatible(pungent_cheese,dessert).
compatible(baking_spices,dessert).
compatible(white_starches,dessert).
compatible(fruit_berries,dessert).
compatible(vanilla_caramel,dessert).
compatible(chocolate_coffee,dessert).
>>>>>>> 22025a38190649c51b304c4a30aa84a8627ed85e
