:- module(facts,[]).

wine(maibec).
wine(syrah).
wine(mourvedre).
wine(pinotage).
wine(petite_sirah).
wine(touriga_nacional).
wine(cabernet_sauvignon).
wine(bordeaux_blend).
wine(meritage).
wine(meriot).
wine(sangiovese).
wine(zinfandel).
wine(cabernet_franc).
wine(tempranillo).
wine(nebbiolo).
wine(barbera).
wine(cotes_du_rhone_blend).
wine(pinot_noir).
wine(grenache).
wine(gamay).
wine(st_laurent).
wine(carignan).
wine(counoise).
wine(provencal_rose).
wine(white_zinfandel).
wine(loire_valley_rose).
wine(pinot_noir_rose).
wine(garnacha_rosadp).
wine(bandol_rose).
wine(tempranillio_rose).
wine(saignee_method_rose).
wine(chardonnay).
wine(semillon).
wine(viognier).
wine(marsanne).
wine(roussanne).
wine(sauvignon_blanc).
wine(albarino).
wine(pinot_blanc).
wine(vermentino).
wine(melon_de_bourgogne).
wine(gargenega).
wine(trebbiano).
wine(pinot_gris).
wine(pinot_grigio).
wine(champagne).
wine(prosecco).
wine(cremant).
wine(cava).
wine(metodo_classico).
wine(sparkling_wine).
wine(sparkling_rose).
wine(moscato).
wine(riesling).
wine(chenin_blanc).
wine(gewurztraminer).
wine(late_harvest_whites).
wine(alsacian_pinot_gris).
wine(port).
wine(sherry).
wine(madeira).
wine(vin_santo).
wine(muscat).
wine(pedro_ximenez).
wineType(bold_red).
wineType(medium_red).
wineType(light_red).
wineType(rose).
wineType(rich_white).
wineType(light_white).
wineType(sparkling).
wineType(sweet_white).
wineType(dessert).
isWineType(maibec,bold_red).
isWineType(syrah,bold_red).
isWineType(mourvedre,bold_red).
isWineType(pinotage,bold_red).
isWineType(petite_sirah,bold_red).
isWineType(touriga_nacional,bold_red).
isWineType(cabernet_sauvignon,bold_red).
isWineType(bordeaux_blend,bold_red).
isWineType(meritage,bold_red).
isWineType(meriot,medium_red).
isWineType(sangiovese,medium_red).
isWineType(zinfandel,medium_red).
isWineType(cabernet_franc,medium_red).
isWineType(tempranillo,medium_red).
isWineType(nebbiolo,medium_red).
isWineType(barbera,medium_red).
isWineType(cotes_du_rhone_blend,medium_red).
isWineType(pinot_noir,light_red).
isWineType(grenache,light_red).
isWineType(gamay,light_red).
isWineType(st_laurent,light_red).
isWineType(carignan,light_red).
isWineType(counoise,light_red).
isWineType(provencal_rose,rose).
isWineType(white_zinfandel,rose).
isWineType(loire_valley_rose,rose).
isWineType(pinot_noir_rose,rose).
isWineType(garnacha_rosadp,rose).
isWineType(bandol_rose,rose).
isWineType(tempranillio_rose,rose).
isWineType(saignee_method_rose,rose).
isWineType(chardonnay,rich_white).
isWineType(semillon,rich_white).
isWineType(viognier,rich_white).
isWineType(marsanne,rich_white).
isWineType(roussanne,rich_white).
isWineType(sauvignon_blanc,light_white).
isWineType(albarino,light_white).
isWineType(pinot_blanc,light_white).
isWineType(vermentino,light_white).
isWineType(melon_de_bourgogne,light_white).
isWineType(gargenega,light_white).
isWineType(trebbiano,light_white).
isWineType(pinot_gris,light_white).
isWineType(pinot_grigio,light_white).
isWineType(champagne,sparkling).
isWineType(prosecco,sparkling).
isWineType(cremant,sparkling).
isWineType(cava,sparkling).
isWineType(metodo_classico,sparkling).
isWineType(sparkling_wine,sparkling).
isWineType(sparkling_rose,sparkling).
isWineType(moscato,sweet_white).
isWineType(riesling,sweet_white).
isWineType(chenin_blanc,sweet_white).
isWineType(gewurztraminer,sweet_white).
isWineType(late_harvest_whites,sweet_white).
isWineType(alsacian_pinot_gris,sweet_white).
isWineType(port,dessert).
isWineType(sherry,dessert).
isWineType(madeira,dessert).
isWineType(vin_santo,dessert).
isWineType(muscat,dessert).
isWineType(pedro_ximenez,dessert).
ingredient(beef).
ingredient(lamb).
ingredient(salami).
ingredient(proscuitto).
ingredient(brosaola).
ingredient(bacon).
ingredient(roast).
ingredient(tenderloin).
ingredient(pork_chop).
ingredient(chicken).
ingredient(duck).
ingredient(turkey).
ingredient(oyster).
ingredient(mussel).
ingredient(clam).
ingredient(tuna).
ingredient(cod).
ingredient(trout).
ingredient(bass).
ingredient(prawn).
ingredient(crab).
ingredient(langoustine).
ingredient(bleu).
ingredient(gargonzola).
ingredient(stilton).
ingredient(green_bean).
ingredient(kale).
ingredient(lettuce).
ingredient(turnip).
ingredient(butternut).
ingredient(pumpkin).
ingredient(delicata).
ingredient(carrot).
ingredient(tomato).
ingredient(eggplant).
ingredient(bell_pepper).
ingredient(crimini).
ingredient(maitake).
ingredient(chenterelle).
ingredient(peanut).
ingredient(almond).
ingredient(pecan).
ingredient(sesame).
ingredient(lentil).
ingredient(navy).
ingredient(pinto).
ingredient(chickpea).
ingredient(black_pepper).
ingredient(ancho).
ingredient(aleppo).
ingredient(chipotle).
ingredient(sichuan).
ingredient(thyme).
ingredient(oregano).
ingredient(basil).
ingredient(tarragon).
ingredient(cinnamon).
ingredient(clove).
ingredient(allspice).
ingredient(mace).
ingredient(anise).
ingredient(turmeric).
ingredient(saffron).
ingredient(fennel).
ingredient(ginger).
ingredient(flour).
ingredient(white_rice).
ingredient(pasta).
ingredient(bread).
ingredient(tortillas).
ingredient(quinoa).
ingredient(farro).
ingredient(brown_rice).
ingredient(sweet_potato).
ingredient(yucca).
ingredient(taro).
ingredient(potato).
ingredient(strawberry).
ingredient(orange).
ingredient(apple).
ingredient(papaya).
ingredient(mango).
ingredient(peach).
ingredient(cherry).
ingredient(banana).
ingredient(creme_brulee).
ingredient(ice_cream).
ingredient(chocolate).
ingredient(coffee).
minorType(red_meat).
minorType(cured_meat).
minorType(pork).
minorType(poultry).
minorType(mollusk).
minorType(fish).
minorType(lobster_shell_fish).
minorType(pungent_cheese).
minorType(green_vegetables).
minorType(root_vegetables).
minorType(nightshades).
minorType(funghi).
minorType(nuts_seeds).
minorType(beans_peas).
minorType(black_pepper).
minorType(hot_spicy).
minorType(herbs).
minorType(baking_spices).
minorType(exotic_aromatic_spices).
minorType(white_starches).
minorType(whole_wheat_grains).
minorType(sweet_starchy_vegetables).
minorType(potato).
minorType(fruit_berries).
minorType(vanilla_caramel).
minorType(chocolate_coffee).
hasMinorType(beef,red_meat).
hasMinorType(lamb,red_meat).
hasMinorType(salami,cured_meat).
hasMinorType(proscuitto,cured_meat).
hasMinorType(brosaola,cured_meat).
hasMinorType(bacon,cured_meat).
hasMinorType(roast, pork).
hasMinorType(tenderloin,pork).
hasMinorType(pork_chop,pork).
hasMinorType(chicken,poultry).
hasMinorType(duck,poultry).
hasMinorType(turkey,poultry).
hasMinorType(oyster,mollusk).
hasMinorType(mussel,mollusk).
hasMinorType(clam,mollusk).
hasMinorType(tuna,fish).
hasMinorType(cod,fish).
hasMinorType(trout,fish).
hasMinorType(bass,fish).
hasMinorType(prawn,lobster_shell_fish).
hasMinorType(crab,lobster_shell_fish).
hasMinorType(langoustine,lobster_shell_fish).
hasMinorType(bleu,pungent_cheese).
hasMinorType(gargonzola,pungent_cheese).
hasMinorType(stilton,pungent_cheese).
hasMinorType(green_bean,green_vegetables).
hasMinorType(kale,green_vegetables).
hasMinorType(lettuce,green_vegetables).
hasMinorType(turnip,root_vegetables).
hasMinorType(butternut,root_vegetables).
hasMinorType(pumpkin,root_vegetables).
hasMinorType(delicata,root_vegetables).
hasMinorType(carrot,root_vegetables).
hasMinorType(tomato,nightshades).
hasMinorType(eggplant,nightshades).
hasMinorType(bell_pepper,nightshades).
hasMinorType(crimini,funghi).
hasMinorType(maitake,funghi).
hasMinorType(chenterelle,funghi).
hasMinorType(peanut,nuts_seeds).
hasMinorType(almond,nuts_seeds).
hasMinorType(pecan,nuts_seeds).
hasMinorType(sesame,nuts_seeds).
hasMinorType(lentil,beans_peas).
hasMinorType(navy,beans_peas).
hasMinorType(pinto,beans_peas).
hasMinorType(chickpea,beans_peas).
hasMinorType(black_pepper,black_pepper).
hasMinorType(ancho,hot_spicy).
hasMinorType(aleppo,hot_spicy).
hasMinorType(chipotle,hot_spicy).
hasMinorType(sichuan,hot_spicy).
hasMinorType(thyme,herbs).
hasMinorType(oregano,herbs).
hasMinorType(basil,herbs).
hasMinorType(tarragon,herbs).
hasMinorType(cinnamon,baking_spices).
hasMinorType(clove,baking_spices).
hasMinorType(allspice,baking_spices).
hasMinorType(mace,baking_spices).
hasMinorType(anise,exotic_aromatic_spices).
hasMinorType(turmeric,exotic_aromatic_spices).
hasMinorType(saffron,exotic_aromatic_spices).
hasMinorType(fennel,exotic_aromatic_spices).
hasMinorType(ginger,exotic_aromatic_spices).
hasMinorType(flour,white_starches).
hasMinorType(white_rice,white_starches).
hasMinorType(pasta,white_starches).
hasMinorType(bread,white_starches).
hasMinorType(tortillas,white_starches).
hasMinorType(quinoa,whole_wheat_grains).
hasMinorType(farro,whole_wheat_grains).
hasMinorType(brown_rice,whole_wheat_grains).
hasMinorType(sweet_potato,sweet_starchy_vegetables).
hasMinorType(yucca,sweet_starchy_vegetables).
hasMinorType(taro,sweet_starchy_vegetables).
hasMinorType(potato,potato).
hasMinorType(strawberry,fruit_berries).
hasMinorType(orange,fruit_berries).
hasMinorType(apple,fruit_berries).
hasMinorType(papaya,fruit_berries).
hasMinorType(mango,fruit_berries).
hasMinorType(peach,fruit_berries).
hasMinorType(cherry,fruit_berries).
hasMinorType(banana,fruit_berries).
hasMinorType(creme_brulee,vanilla_caramel).
hasMinorType(ice_cream,vanilla_caramel).
hasMinorType(chocolate,chocolate_coffee).
hasMinorType(coffee,chocolate_coffee).
majorType(meat).
majorType(fish).
majorType(dairy).
majorType(vegetable).
majorType(herb_spice).
majorType(starch).
majorType(sweet).
hasMajorType(red_meat,meat).
hasMajorType(cured_meat,meat).
hasMajorType(pork,meat).
hasMajorType(poultry,meat).
hasMajorType(mollusk,meat).
hasMajorType(fish,meat).
hasMajorType(lobster_shell_fish,fish).
hasMajorType(soft_cheese,dairy).
hasMajorType(cream,dairy).
hasMajorType(pungent_cheese,dairy).
hasMajorType(hard_cheese,dairy).
hasMajorType(alliums,vegetable).
hasMajorType(green_vegetables,vegetable).
hasMajorType(root_vegetables,vegetable).
hasMajorType(nightshades,vegetable).
hasMajorType(funghi,vegetable).
hasMajorType(nuts_seeds,vegetable).
hasMajorType(beans_peas,vegetable).
hasMajorType(black_pepper,herb_spice).
hasMajorType(red_pepper,herb_spice).
hasMajorType(hot_spicy,herb_spice).
hasMajorType(herbs,herb_spice).
hasMajorType(baking_spices,herb_spice).
hasMajorType(exotic_aromatic_spices,herb_spice).
hasMajorType(white_starches,starch).
hasMajorType(whole_wheat_grains,starch).
hasMajorType(sweet_starchy_vegetables,starch).
hasMajorType(potato,starch).
hasMajorType(fruit_berries,sweet).
hasMajorType(vanilla_caramel,sweet).
hasMajorType(chocolate_coffee,sweet).
compatible(red_meat,bold_red).
compatible(cured_meat,bold_red).
compatible(pork,bold_red).
compatible(pungent_cheese,bold_red).
compatible(hard_cheese,bold_red).
compatible(alliums,bold_red).
compatible(nightshades,bold_red).
compatible(funghi,bold_red).
compatible(black_pepper,bold_red).
compatible(red_pepper,bold_red).
compatible(white_starches,bold_red).
compatible(potato,bold_red).
compatible(red_meat,medium_red).
compatible(cured_meat,medium_red).
compatible(pork,medium_red).
compatible(soft_cheese_cream,medium_red).
compatible(pungent_cheese,medium_red).
compatible(hard_cheese,medium_red).
compatible(alliums,medium_red).
compatible(nightshades,medium_red).
compatible(funghi,medium_red).
compatible(beans_peas,medium_red).
compatible(black_pepper,medium_red).
compatible(herbs,medium_red).
compatible(baking_spices,medium_red).
compatible(exotic_aromatic_spices,medium_red).
compatible(white_starches,medium_red).
compatible(potato,medium_red).
compatible(cured_meat,light_red).
compatible(poultry,light_red).
compatible(soft_cheese_cream,light_red).
compatible(alliums,light_red).
compatible(funghi,light_red).
compatible(nuts_seeds,light_red).
compatible(herbs,light_red).
compatible(exotic_aromatic_spices,light_red).
compatible(white_starches,light_red).
compatible(whole_wheat_grains,light_red).
compatible(potato,light_red).
compatible(cured_meat,rose).
compatible(pork,rose).
compatible(poultry,rose).
compatible(soft_cheese_cream,rose).
compatible(pungent_cheese,rose).
compatible(hard_cheese,rose).
compatible(alliums,rose).
compatible(root_vegetables,rose).
compatible(nightshades,rose).
compatible(nuts_seeds,rose).
compatible(beans_peas,rose).
compatible(red_pepper,rose).
compatible(herbs,rose).
compatible(baking_spices,rose).
compatible(exotic_aromatic_spices,rose).
compatible(white_starches,rose).
compatible(whole_wheat_grains,rose).
compatible(sweet_starchy_vegetables,rose).
compatible(potato,rose).
compatible(poultry,rich_white).
compatible(fish,rich_white).
compatible(lobster_shell_fish,rich_white).
compatible(soft_cheese_cream,rich_white).
compatible(hard_cheese,rich_white).
compatible(alliums,rich_white).
compatible(root_vegetables,rich_white).
compatible(funghi,rich_white).
compatible(nuts_seeds,rich_white).
compatible(herbs,rich_white).
compatible(white_starches,rich_white).
compatible(whole_wheat_grains,rich_white).
compatible(potato,rich_white).
compatible(poultry,sparkling).
compatible(mollusk,sparkling).
compatible(fish,sparkling).
compatible(lobster_shell_fish,sparkling).
compatible(soft_cheese_cream,sparkling).
compatible(pungent_cheese,sparkling).
compatible(alliums,sparkling).
compatible(green_vegetables,sparkling).
compatible(nuts_seeds,sparkling).
compatible(beans_peas,sparkling).
compatible(red_pepper,sparkling).
compatible(hot_spicy,sparkling).
compatible(herbs,sparkling).
compatible(white_starches,sparkling).
compatible(potato,sparkling).
compatible(cured_meat,sweet_white).
compatible(lobster_shell_fish,sweet_white).
compatible(soft_cheese_cream,sweet_white).
compatible(pungent_cheese,sweet_white).
compatible(alliums,sweet_white).
compatible(root_vegetables,sweet_white).
compatible(nightshades,sweet_white).
compatible(nuts_seeds,sweet_white).
compatible(red_pepper,sweet_white).
compatible(hot_spicy,sweet_white).
compatible(baking_spices,sweet_white).
compatible(exotic_aromatic_spices,sweet_white).
compatible(white_starches,sweet_white).
compatible(whole_wheat_grains,sweet_white).
compatible(sweet_starchy_vegetables,sweet_white).
compatible(potato,sweet_white).
compatible(fruit_berries,sweet_white).
compatible(vanilla_caramel,sweet_white).
compatible(cured_meat,dessert).
compatible(soft_cheese_cream,dessert).
compatible(pungent_cheese,dessert).
compatible(baking_spices,dessert).
compatible(white_starches,dessert).
compatible(fruit_berries,dessert).
compatible(vanilla_caramel,dessert).
compatible(chocolate_coffee,dessert).
